name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *' # Runs once every day
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: YousefABDELRAZEK
          svg_out_path: github-contribution-grid-snake.svg

